// Useful Spanish<->Hebrew connector phrases for real conversations
// (travel, ordering food, asking for help), separate from the single-word deck.
// Same shape as WORDS ({id, es, he, rank}) but with ids starting at 10001 so
// progress never collides with the word list's ids (1-500) in localStorage.
const PHRASES = [
  { id: 10001, es: "Quiero...", he: "אני רוצה...", rank: 1 },
  { id: 10002, es: "Necesito...", he: "אני צריך/ה...", rank: 2 },
  { id: 10003, es: "¿A qué hora?", he: "באיזו שעה?", rank: 3 },
  { id: 10004, es: "¿Dónde está...?", he: "איפה נמצא...?", rank: 4 },
  { id: 10005, es: "¿Cuánto cuesta?", he: "כמה זה עולה?", rank: 5 },
  { id: 10006, es: "No entiendo", he: "אני לא מבין/ה", rank: 6 },
  { id: 10007, es: "¿Puede ayudarme?", he: "תוכל/י לעזור לי?", rank: 7 },
  { id: 10008, es: "¿Habla inglés?", he: "אתה מדבר אנגלית?", rank: 8 },
  { id: 10009, es: "¿Dónde está el baño?", he: "איפה השירותים?", rank: 9 },
  { id: 10010, es: "¿Dónde está la estación?", he: "איפה התחנה?", rank: 10 },
  { id: 10011, es: "Estoy perdido/a", he: "אני אבוד/ה", rank: 11 },
  { id: 10012, es: "¿Puede repetir, por favor?", he: "אפשר לחזור על זה בבקשה?", rank: 12 },
  { id: 10013, es: "Un momento, por favor", he: "רגע, בבקשה", rank: 13 },
  { id: 10014, es: "¿Cómo llego a...?", he: "איך אני מגיע/ה ל...?", rank: 14 },
  { id: 10015, es: "¿Está lejos?", he: "זה רחוק?", rank: 15 },
  { id: 10016, es: "¿Está cerca?", he: "זה קרוב?", rank: 16 },
  { id: 10017, es: "Estoy buscando...", he: "אני מחפש/ת...", rank: 17 },
  { id: 10018, es: "Me gustaría...", he: "הייתי רוצה...", rank: 18 },
  { id: 10019, es: "La cuenta, por favor", he: "החשבון, בבקשה", rank: 19 },
  { id: 10020, es: "¿Qué recomienda?", he: "מה אתה ממליץ?", rank: 20 },
  { id: 10021, es: "¿Puedo ver el menú?", he: "אפשר לראות את התפריט?", rank: 21 },
  { id: 10022, es: "Quisiera una mesa para dos", he: "אני רוצה שולחן לשניים", rank: 22 },
  { id: 10023, es: "Sin azúcar, por favor", he: "בלי סוכר, בבקשה", rank: 23 },
  { id: 10024, es: "No como carne", he: "אני לא אוכל/ת בשר", rank: 24 },
  { id: 10025, es: "Soy alérgico/a a...", he: "יש לי אלרגיה ל...", rank: 25 },
  { id: 10026, es: "¿Puedo pagar con tarjeta?", he: "אפשר לשלם בכרטיס?", rank: 26 },
  { id: 10027, es: "¿Tiene wifi?", he: "יש כאן וויפיי?", rank: 27 },
  { id: 10028, es: "¿Cuál es la contraseña del wifi?", he: "מה הסיסמה לוויפיי?", rank: 28 },
  { id: 10029, es: "¿A qué hora abre?", he: "באיזו שעה זה נפתח?", rank: 29 },
  { id: 10030, es: "¿A qué hora cierra?", he: "באיזו שעה זה נסגר?", rank: 30 },
  { id: 10031, es: "¿Dónde está la parada de autobús?", he: "איפה תחנת האוטובוס?", rank: 31 },
  { id: 10032, es: "¿A qué hora sale el próximo tren?", he: "באיזו שעה יוצאת הרכבת הבאה?", rank: 32 },
  { id: 10033, es: "¿Puede hablar más despacio?", he: "אפשר לדבר יותר לאט?", rank: 33 },
  { id: 10034, es: "No hablo español muy bien", he: "אני לא מדבר/ת ספרדית טוב", rank: 34 },
  { id: 10035, es: "¿Dónde puedo encontrar un taxi?", he: "איפה אני יכול/ה למצוא מונית?", rank: 35 },
  { id: 10036, es: "Lléveme aquí, por favor", he: "קח אותי לכאן, בבקשה", rank: 36 },
  { id: 10037, es: "¿Cuánto falta para llegar?", he: "כמה זמן נשאר עד שנגיע?", rank: 37 },
  { id: 10038, es: "Necesito un médico", he: "אני צריך/ה רופא", rank: 38 },
  { id: 10039, es: "¿Dónde está el hospital?", he: "איפה בית החולים?", rank: 39 },
  { id: 10040, es: "Me duele aquí", he: "כואב לי כאן", rank: 40 },
  { id: 10041, es: "Llame a la policía, por favor", he: "תתקשר/י למשטרה, בבקשה", rank: 41 },
  { id: 10042, es: "Quisiera reservar una habitación", he: "הייתי רוצה להזמין חדר", rank: 42 },
  { id: 10043, es: "¿Tiene una habitación libre?", he: "יש חדר פנוי?", rank: 43 },
  { id: 10044, es: "¿Puedo tomar una foto?", he: "אפשר לצלם תמונה?", rank: 44 },
  { id: 10045, es: "Vengo de Israel", he: "אני מגיע/ה מישראל", rank: 45 },
  { id: 10046, es: "Es un placer conocerte", he: "נעים להכיר אותך", rank: 46 },
  { id: 10047, es: "Nos vemos mañana", he: "נתראה מחר", rank: 47 },
  { id: 10048, es: "¿Puede escribirlo, por favor?", he: "אפשר לכתוב את זה, בבקשה?", rank: 48 },
  { id: 10049, es: "Todo bien, gracias", he: "הכל טוב, תודה", rank: 49 },
  { id: 10050, es: "Que tengas un buen día", he: "שיהיה לך יום טוב", rank: 50 },
];
